debug: true

server:
  port: 8086
grpc:
  server:
    name: localhost
    port: 8087

spring:
  application:
    name: employee
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      hbm2ddl:
        auto: validate

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    initialization-mode: always