debug: true

server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true 

  application:
    name: employee

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      hbm2ddl:
        auto: validate

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: administrator
    driverClassName: org.h2.Driver
    initialization-mode: always

  h2:
    console:
      enabled: true