server:
  port: 8086

debug: true

spring:
  application:
    name: employee
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      hbm2ddl:
        auto: update

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

    h2:
      console:
        enable: true